using System;
using System.Collections.Generic;
using UnityEngine;

public sealed class EventManager
{
	public enum EventType
	{
		none = -1,
		ShopPanel_BuyGiftPackege = 20000,
		MainPanel_BuildingTimeShow = 1,
		MainPanel_MilitaryRank,
		MainPanel_MilitaryRank_GiftGet,
		MainPanel_MilitaryRank_GiftPanel_Close,
		MainPanel_OpenPlayerInfo,
		MainPanel_OpenItemBox,
		MainPanel_OpenTopTen,
		MainPanle_CloseTopTen = 3001,
		MainPanel_OpenBattle = 8,
		MainPanel_MenuBtn = 10,
		MainPanel_MessageBtn,
		MainPanel_GoToWorld,
		MainPanel_OpenBuildingStore,
		MainPanel_ArmsDealer,
		MainPanel_SendMessage,
		MainPanel_Task,
		MainPanel_Achievement,
		MainPanel_ClickCoin,
		MainPanel_ClickOil,
		MainPanel_ClickSteel,
		MainPanel_ClickRareEarth,
		MainPanel_SystemMessage,
		MainPanel_FamilyMessage,
		MainPanel_WorldMessage,
		MainPanel_Email,
		MainPanel_Sign,
		MainPanel_MainTaskTittle,
		MainPanel_AddProde,
		MainPanel_AddMilitary,
		MainPanel_VipTips,
		MainPanel_JiangPaiTips,
		MainPanel_OfficerDegree,
		MainPanel_AddArrmyClick,
		MainPanel_ElectricityInfo,
		MainPanel_ZuoCeBtnClick,
		MainPanel_TaskTypePanel,
		MainPanel_SynopsisTaskPanel,
		MainPanel_AddBuildingQueue,
		MainPanel_TakeAllRes,
		MainPanel_CloseBuildingMovingOrInBuilding,
		MainPanel_GameAnnouncement,
		MainPanel_OpenScretShop,
		MainPanel_GoToPVP,
		MainPanel_OnLine,
		MainPanel_PlayerInfo,
		MainPanel_GotoBuildingState,
		MainPanel_OpenActivity,
		MainPanel_OpenExchangeGift,
		MainPanel_OpenChargeActitys,
		MainPanel_FIRST,
		MainPanel_SECOND,
		MainPanel_OpenArmyClick,
		MainPanel_OpenArmyMemberPanel,
		MainPanel_SendApply,
		MainPanel_Activity_Left,
		MainPanel_Activity_Right,
		MainPanel_OpenShouChong,
		MainPanel_Open1YuanGou,
		MainPanel_GoToBattle,
		MainPanel_LossArmyMessageClose,
		MainPanel_PVPNewMessageClose,
		MainPanel_OpenShop,
		MainPanel_OpenVip,
		MainPanel_OpenMonthlyCard,
		MainPanel_OpenDearShop,
		MainPanel_OpenBaseGifePanel,
		MainPanel_OpenVip_PuTong,
		MainPanel_OpenVip_ZhiZun,
		ZhaoMuPanel_Close = 100,
		ZhaoMuPanel_P_ZuanShi,
		ZhaoMuPanel_P_WuPin,
		ZhaoMuPanel_J_ZuanShi,
		ZhaoMuPanel_J_WuPin,
		ZhaoMuPanel_C_ZuanShi,
		ZhaoMuPanel_Officer,
		ZhaoMuPanel_CollectItem = 110,
		ZhaoMuPanel_P_Free,
		ZhaoMuPanel_J_Free,
		ZhaoMuPanel_C_WuPin,
		ZhaoMuPanel_C_DongJie,
		ZhaomuPanel_Item,
		ZhaomuPanel_Shilianchou,
		ZhaomuPanel_CloseShilianchou,
		ZhaomuPanel_ItemPanelShowBtnClick,
		MonthlyCard_PutongBuy = 120,
		MonthlyCard_ZhiZunBuy,
		MonthlyCard_ClosePanel = 126,
		VIPPanel_ChongZhiTiaoZhuan = 122,
		VIPPanel_LingQuJiangLi,
		VIPPanel_Next,
		VIPPanel_Pre,
		VIPPanel_ClosePanel = 127,
		VIPPanel_ChongZhi,
		BattleReportPanel_Close = 201,
		BattleReportPanel_JinGong,
		BattleReportPanel_FangShou,
		BattleReportPanel_Daily,
		BattleReportPanel_Details,
		BattleReportPanel_ViewBattle,
		BattleReportPanel_ShareMovie,
		BattleReportPanel_Revenge,
		BattleReportPanel_GetBack,
		BattleReportPanel_GoAround,
		BattleReportPanel_Fire,
		BattleReportPanel_Tween,
		BattleReportPanel_GetMoney,
		GuYongPanel_GuYong = 301,
		GuYongPanel_QianSan,
		GuYongPanel_Close,
		GuYongPanel_Replace_Ok,
		GuYongPanel_Replace_Cancel,
		GuYongPanel_MixItem,
		OfficerPanle_Close = 400,
		OfficePanel_ChangePage,
		OfficePanel_QianSan,
		OfficePanel_UseItem,
		OfficePanel_Officer,
		QianSanPanel_Close,
		QianSanPanel_OperOK,
		QianSanPanel_OperCancel,
		OfficerPanel_OfficerDegreeItemClick,
		OfficerPanel_OfficerDegreePanelClose,
		OfficerPanel_OfficerDegreeClick,
		OfficerPanel_OfficerDegreePanelClick,
		OfficerPanel_OfficerDegreeOkPanelClose,
		OfficerPanel_OfficerLevelUpClick,
		OfficerPanel_OfficerLevelhintPanelClose,
		OfficerPanel_OfficerLevelUpdateClick,
		OfficerPanel_OfficerUpdatePanelClose,
		OfficerPanel_OfficerItemPanelClose,
		OfficerPanel_OfficerMainPanelShow,
		OfficerPanel_OfficerItemClickShow,
		T_CommandPanel_Info = 500,
		T_CommandPanel_Other,
		T_CommandPanel_Update,
		T_CommandPanel_Remove,
		T_CommandPanel_AddArmyAuto,
		T_CommandPanel_BuildYes,
		T_CommandPanel_BuildCancel,
		T_CommandPanel_EndAideCompound,
		T_CommandPanel_UpdateBuild,
		T_CommandPanel_OpenDefensiveCover,
		T_CommandPanel_Chouqu,
		T_CommandPanel_Zhuangbei,
		T_CommandPanel_JiChangPeiBing,
		T_CommandPanel_ConvertSkill,
		T_CommandPanel_UpdateSkill,
		T_CommandPanel_TowerUpgrade,
		T_CommandPanel_TowerStrength,
		T_CommandPanel_BuildingUpGrade,
		T_CommandPanel_AddSoliderFight,
		T_CommandPanel_AddAirFight,
		Building_WallLine,
		Building_WallRatate,
		Building_EndCD,
		T_CommandPanel_UpdateBatches,
		T_CommandPanel_ChangeSolider,
		T_CommandPanel_Apply,
		ArmyFuncPanel_ArmyFunc = 530,
		ArmyFuncPanel_ArmyCancle,
		ArmyFuncPanel_ArmyFuncEnd,
		ArmyFuncPanel_SellArmyFuncEnd,
		ArmyControlPanel_ChangeArmyType = 600,
		ArmyControlPanel_AddArmy,
		ArmyControlPanel_GoBack,
		ArmyControlPanel_FuncArmy,
		ArmyControlPanel_ArmyInfo,
		ArmyControlpanel_UpdateLeve,
		ArmyControlpanel_UpdateBack,
		ArmyControlpanel_QieHuan,
		ArmyControlpanel_InfoPanelClose,
		ArmyNewControlpanel_Close = 610,
		ArmyNewControlpanel_Update,
		ArmyNewControlpanel_MoveLeft,
		ArmyNewControlpanel_MoveRight,
		ArmyNewControlpanel_UpdateEnd,
		ArmyNewControlpanel_FuncEnd,
		ArmyNewControlpanel_FuncArmy,
		BuildingStore_EconomyBtn = 700,
		BuildingStore_defenseBtn,
		BuildingStore_supportBtn,
		BuildingStore_ItemClick,
		BuildingStore_ItemClose,
		BuildingStore_ItemInfoClick,
		BuildingStore_ItemInfoCloseClick,
		BuildingStore_ItemInfo_TryBuilding,
		ArmsDearPanel_RereshBtnClick = 10000,
		BattlePanel_GoWarZone = 800,
		BattlePanel_GoBattleField,
		BattlePanel_SweepOne,
		BattlePanel_SweepTen,
		BattlePanel_CloseBattleFightUIInfo,
		BattlePanel_CloseBattleUIInfo,
		BattlePanel_GoToFight,
		BattlePanel_ClosePanle,
		BattlePanel_NextBattlePanel,
		BattlePanel_PreBattlePanel,
		BattlePanel_OnePrize,
		BattlePanel_TwoPrize,
		BattlePanel_ThreePrize,
		BattlePanel_CloseTips,
		BattlePanel_Section,
		BattlePanel_CloseNotarize,
		BattlePanel_battleItem,
		BattlePanel_CloseTollgate,
		battlePanel_CloseGotoFight,
		BattlePanrl_NewBackBtn,
		BattlePanel_BuyJunlingBtn,
		BattlePanel_addNum,
		WorldMap_BackHome = 900,
		WorldMap_Enter,
		WorldMap_Spy,
		WorldMap_Warring,
		WorldMap_Watch,
		WorldMap_ReFind,
		WorldMap_Info,
		WorldMap_OpenCloud,
		WorldMap_QuickWarring,
		WorldMap_OpenMiniMap = 920,
		WorldMap_CloseMiniMap,
		SpyPanel_Attack = 1000,
		SpyPanel_Back = 1002,
		SpyPanel_BtnSearch = 1005,
		FightPanel_ForceMove = 1100,
		FightPanel_Landing,
		FightPanel_UseSupperSkill,
		FightPanel_Retreat,
		FightPanel_AutoFight = 1014,
		FightPanel_officerInfo,
		FightPanel_SendSoidler,
		FightPanel_SendSoidlerAuto,
		FightPanel_ShowSkillClick,
		FightPanle_UIItemClick,
		FightPanle_ChangeSolider,
		FightPanle_IsControlSolider,
		FightPanel_AirCameraCancel = 1023,
		SettlePanel_Close = 1200,
		SettlePanel_Failure,
		SettlePanel_CloseTips,
		SettlePanel_WinClick,
		SettlePanel_LoseClick,
		TaskPane_BackClick = 1301,
		TaskPane_principal_lineClick,
		TaskPane_principal_DayClick,
		TaskPane_principal_GetClick = 1303,
		TaskPane_achievementGetClick,
		TaskPane_Principal_lineGet,
		TaskPane_Principal_LingQu,
		TaskPane_Principal_TipsShow,
		TaskPane_SynopsisTaskClose,
		TaskPane_SynopsisTaskTiaoZhuan,
		NewTaskPanel_DailyTask,
		NewTaskPanel_MainTask,
		NewTaskPanel_GetMainTaskBtn,
		NewTaskPanel_GetDailyTaskBtn,
		NewTaskPanel_ClosePanel,
		NewTaskPanel_Skip,
		HomeUpOpenBuildingAndArmy_Close = 1400,
		TechnologyUpdate_ArmyBtn,
		TechnologyUpdate_TowerBtn,
		TechnologyUpdate_EconomyBtn,
		TechnologyUpdate_ItemSpBtn,
		TechnologyUpdate_Close,
		TechnologyUpdateTreePanel_Close = 1410,
		TechnologyUpdateTreePanel_Btn_Economy,
		TechnologyUpdateTreePanel_Btn_Defense,
		TechnologyUpdateTreePanel_Btn_Attack,
		TechnologyUpdateTreePanel_Ponit,
		TechnologyUpdateTreePanel_DoWork,
		Expense_GetBtn = 1501,
		Expense_ClosePanel,
		T_InfoPanel_Upgrade = 1500,
		T_InfoPanel_BackClick = 1503,
		TechnoButtonCompound_Btn = 1600,
		TechUpdatingEnd = 1602,
		UpdateSoliderSkill_Btn = 1601,
		EnemyPanel_DetecBtn = 1700,
		EnemyPanel_AttackBtn,
		EnemyPanel_Close,
		EnemyPanel_CloseEnemyShow,
		EnemyPanel_OpenPanel,
		EnemyPanel_CloseScorePanel,
		MessageBoxClose_btn1Click = 1800,
		MessageBoxClose_btn2Click,
		MessageBoxClose_btn3Click,
		EquipPanel_OpenClothesEquip = 1900,
		EquipPanel_OpenWeaponEquip,
		EquipPanel_OpenRankEquip,
		EquipPanel_ClosePanel,
		EquipPanel_PutOnEquip,
		ReserveDutyPanle_AddBtn = 2000,
		ReserveDutyPanle_LessenBtn,
		ReserveDutyPanle_DetermineBtn,
		ReserveDutyPanle_CloseBtn,
		ReserveDutyPanle_OpenBtn,
		ZhanyijianzhutishiPanel_Close = 2100,
		TimeEndClick = 2200,
		TimeEndClick_ArmyFuncEnd = 2210,
		GetAwardPanelClose = 2300,
		ShangChengClick = 2400,
		CloseParsonDes = 2500,
		CloseHand,
		SkillExtractPanel_ItemPanelShowBtnClick = 2600,
		SkillExtractPanel_One,
		SkillExtractPanel_Ten,
		SkillExtractPanel_CloseSkillShow,
		SkillExtractPanel_ItemClick,
		SkillExtractPanel_GoInDuiHuanPanel,
		SkillExtractPanel_Close,
		SkillExtractPanel_CloseDuiHuan,
		SkillEquipmentPanel_Close,
		SkillEquipmentPanel_SkillSold,
		SkillExtractPanel_DuiHuanItemClick,
		SkillExtractPanel_AddNormalTimes,
		SkillExtractPanel_AddSpecialTimes,
		SkillExtractPanel_Primary = 2620,
		SkillExtractPanel_Intermediate,
		SkillExtractPanel_Senior,
		SkillExtractPanel_PrimaryEndCDTime,
		SkillExtractPanel_IntermediateEndCDTime = 2625,
		SkillExtractPanel_SeniorEndCDTime,
		ShopPanel_ClosePanel = 7000,
		ItemPanelCheChengPanelClose = 3000,
		Config_WarPanel_ConfigAuto = 3101,
		Config_WarPanel_Yes,
		Config_WarPanel_ComandoOpenList,
		Config_WarPanel_SelectComando,
		Config_WarPanel_Back,
		Config_WarPanel_ComandoReLive,
		Config_WarPanel_LockSoldier,
		Config_WarPanel_LockSkill,
		Config_WarPanel_LockAir,
		Config_WarPanel_ADCArmy,
		Config_WarPanel_ADCAir,
		AidePanel_Cancle = 5001,
		AdjutantPanle_Close,
		LoginPanel_DownList = 6000,
		LoginPanel_LoginGameBtn,
		LoginPanel_ClearUserName,
		LoginPanel_ChooseUser,
		LoginPanel_Register,
		LoingPanel_RemberUserAccount,
		LoginPanel_AutoLogin,
		LoginPanel_ChooseServer,
		LoginPanel_EnterGame,
		LoginPanel_ChooseServerArea,
		LoginPanel_SelectedServer,
		LoginPanel_ExitGame,
		LoginPanel_ChooseUserName,
		LoginPanel_ChangeUser,
		LoginPanel_CloseServerPanel,
		LoginPanel_CloseChooseUserName,
		LoginPanel_ChangeServerTeam,
		SignPanel_Sign = 8000,
		TechnologyPanle_CloseTehcnology,
		ArmsDearlPanel_CloseArms,
		ToptenPanel_CloseTop,
		ToptenPanle_VistiteSomeOne,
		ToptenPanel_ToptenShow,
		ToptenPanel_ToptenPrze,
		ToptemPanel_GoodFriend,
		ToptenPanel_GetTopTenAward,
		Shop_TypeBtnA = 8010,
		Shop_TypeBtnB,
		Shop_PageBtn_Left,
		Shop_PageBtn_Right,
		ConfirmalPanel_Suer = 9003,
		ConfirmalPanel_Canel,
		RandomNamePanel_RandomName = 9100,
		RandomNamePanel_RandomNameSure,
		ShowAwardPanelManager_SureClick = 9200,
		BattleBoxPickup = 9300,
		BattleBoxBack,
		BattelBoxClosePanel,
		EliteBattleBox,
		TakeAllResPanel_SureBtn = 9400,
		TakeAllResPanel_CancleBtn,
		NewConvertPanel_ClosePanel = 9501,
		NewConvertPanel_DuiHunClick,
		NewSkillUpdatePanel_Update = 9601,
		NewSkillUpdatePanel_Close,
		NewSkillUpdatePanel_SkillClick,
		GameAnnouncement_ClosePanel = 9701,
		PVP_FindFighter = 9801,
		PVP_FindFighter_Again,
		PVP_Fight,
		PVP_BackHome,
		PVPMessage_Open = 9811,
		PVPMessage_Close,
		PVPMessage_AttType,
		PVPMessage_DefType,
		PVPMessage_FightBack,
		PVPMessage_FightWatch,
		ShowPlayerLevelPanel_CloseThis = 9901,
		PlayerInfoPanel_Close = 10001,
		PlayerInfoPanel_LoginAgain,
		PlayerInfoPanel_Exit,
		PlayerInfoPanel_CloseMusic,
		PlayerInfoPanel_CloseMusicEffect,
		PlayerInfoPanel_LanguageChange,
		SepcialSoliderPanel_Close = 10101,
		SepcialSoliderPanel_OpenSkill,
		SepcialSoliderPanel_OpenExp,
		SepcialSoliderPanel_updateSkill,
		SepcialSoliderPanel_updateSolider,
		SepcialSoliderPanel_updateStar,
		SepcialSoliderPanel_UserExpItem,
		SepcialSoliderPanel_otherClick,
		SepcialSoliderPanel_UseReliveRMB,
		SepcialSoliderPanel_BuySoliderRMB,
		SepcialSoliderPanel_MoveLeft,
		SepcialSoliderPanel_MoveRight,
		SepcialSoliderPanel_FuncArmy,
		TowerStrengthPanel_Colse = 10201,
		TowerStrengthPanel_Strength,
		TowerUpdatePanel_Close,
		TowerUpdatePanel_UpGrade,
		BuildingUpGradePanel_BtnGrade,
		BuildingUpGradePanel_Close,
		ActivityPanelManager_Close = 10301,
		ActivityPanelManager_SevenDay,
		ActivityPanelManager_Online,
		ActivityPanelManager_EveryDay,
		ActivityPanelManager_Level,
		ActivityPanelManager_Home,
		ActivityPanelManager_Top,
		ActivityPanelManager_Battle,
		ActivityPanelManager_Other,
		ActivityPanelManager_Watch,
		ActivityPanelManager_GetAward,
		ActivityPanelManager_GetOnlineAward,
		ActivityPanelManager_GetEveryDayTask,
		ActivityPanelManager_GetLevelAward,
		ActivityPanelManager_GetHomeAward,
		ActivityPanelManager_GetBattleAward,
		ActivityPanelManager_GetTopAward,
		ActivityPanelManager_GetOtherAward,
		ActivityPanelManager_GetMonye,
		ActivityPanelManager_GetEveryDayTaskSkip,
		BaseGiftPanel_GetBtn,
		BaseGiftPanel_Close = 10323,
		ChargeActityPanel_Close = 10401,
		ChargeActityPnael_Get10,
		ChargeActityPnael_Get10All,
		ChargeActityPnael_Get11 = 10405,
		ChargeActityPnael_Get14,
		ChargeActityPnael_Buy18 = 10404,
		ChargeActityPnael_Get18 = 10407,
		ChargeActityPnael_Get19_One,
		ChargeActityPnael_Charge,
		ChargeActityPnael_Get19_Ten,
		ChargeActityPnael_Get12,
		ChargeActityPanel_LeftBtnClick,
		ChargeActityPnael_Get15,
		ChargeActityPnael_Get13 = 10415,
		ChargeActityPnael_Get16,
		ChargeActityPnael_Get17,
		ChargeActityPnael_Charge_NotByShop,
		ChargeActityPnael_RecieveActity_SingleType,
		ArmyGroupManager_ChooseArmyIcon = 10499,
		ArmyGroupManager_ClosePanel,
		ArmyGroupManager_OpenPanel,
		ArmyGroupManager_EnterArmy,
		ArmyGroupManager_CreatArmy,
		ArmyGroupManager_SearchArmy,
		ArmyGroupManager_OpenSearchArmyPanel,
		ArmyGroupManager_ChangeArmy,
		ArmyGroupManager_HideCreateArmy,
		ArmyGroupManager_SetArmyIcon,
		ArmyGroupManager_CloseCreatArmyPanel,
		ArmyGroupManager_ClseeSearchArmyPanel,
		ArmyPeopleManager_ClosePanel,
		ArmyPeopleManager_BtnDeleltMember,
		ArmyPeopleManager_BtnVisite,
		ArmyPeopleManager_BtnChangeJob,
		ArmyPeopleManager_BtnArmyMember,
		ArmyPeopleManager_BtnArmyAward,
		ArmyPeopleManager_BtnArmyDuplicate,
		ArmyPeopleManager_BtnArmySubmit,
		ArmyPeopleManager_BtnExitArmy,
		ArmyPeopleManager_BtnDissolve,
		ArmyPeopleManager_BtnAgreeSubmit,
		ArmyPeopleManager_BtnNoAgreeSubmit,
		ArmyPeopleManager_BtnVisitSubmit,
		ArmyPeopleManager_BtnClearSubmit,
		ArmyPeopleManager_ChangeLegionIcon,
		ArmyPeopleManager_EditLegionDes,
		ArmyPeopleManager_ChangeLegionOpenType,
		ArmyPeopleManager_SureChangeIcon,
		ArmyPeopleManager_CancleChangeIcon,
		ArmyGroupManager_SureCreatArmy,
		LegionBattleButton,
		LegionBattleEnter,
		LegionBattleBack,
		Geo_Earth_Back,
		Geo_Star_Btn,
		Change_NormalBattleBtn,
		Change_LegionBattleBtn,
		BattlePassed_BtnA,
		BattlePassed_BtnB,
		TaskByNewBie = 11000,
		TaskByNewBie_Get,
		TaskBySide,
		TaskBySide_Get,
		Bag_UseItem = 11100
	}

	public delegate void VoidDelegate(GameObject go);

	private static EventManager instance;

	private Dictionary<int, EventManager.VoidDelegate> EventDic = new Dictionary<int, EventManager.VoidDelegate>();

	public static EventManager Instance
	{
		get
		{
			if (EventManager.instance == null)
			{
				EventManager.instance = new EventManager();
				EventManager.instance.AddEvent(EventManager.EventType.none, delegate(GameObject go)
				{
				});
			}
			return EventManager.instance;
		}
	}

	private EventManager()
	{
	}

	public void DispatchEvent(EventManager.EventType type, GameObject go)
	{
		if (this.EventDic.ContainsKey((int)type))
		{
			this.EventDic[(int)type](go);
		}
		else
		{
			LogManage.Log("严重错误，事件不存在：" + type.ToString());
		}
	}

	public void ChangeEvent(EventManager.EventType type, EventManager.VoidDelegate newEvent)
	{
		if (this.EventDic.ContainsKey((int)type))
		{
			this.EventDic[(int)type] = newEvent;
		}
	}

	public void AddEvent(EventManager.EventType type, EventManager.VoidDelegate thisEvent)
	{
		if (!this.EventDic.ContainsKey((int)type))
		{
			this.EventDic[(int)type] = thisEvent;
		}
		else
		{
			this.ChangeEvent(type, thisEvent);
		}
	}

	public void ClearEvent()
	{
		this.EventDic.Clear();
	}
}
